# Generated by Django 4.2.7 on 2025-10-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poblacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('tipo_registro', models.CharField(help_text='Tipo de registro (ej: consulta, vacunación)', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_salud', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Registro de Salud',
                'verbose_name_plural': 'Registros de Salud',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ControlSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_control', models.CharField(help_text='Tipo de control (ej: vacunación, chequeo)', max_length=100)),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_salud', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Control de Salud',
                'verbose_name_plural': 'Controles de Salud',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='AlertaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('fecha_alerta', models.DateField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_salud', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Alerta de Salud',
                'verbose_name_plural': 'Alertas de Salud',
                'ordering': ['-fecha_alerta'],
            },
        ),
    ]
