# Generated by Django 4.2.7 on 2025-11-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0003_grupoetnico_remove_persona_grupo_familiar_and_more'),
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(help_text='Nombre de la vacuna', max_length=200)),
                ('tipo_vacuna', models.CharField(choices=[('rutinaria', 'Rutinaria'), ('campana', 'Campaña'), ('especial', 'Especial')], default='rutinaria', max_length=20)),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.CharField(blank=True, help_text='Número de dosis o descripción', max_length=50, null=True)),
                ('lote', models.CharField(blank=True, help_text='Lote de la vacuna', max_length=100, null=True)),
                ('profesional_salud', models.CharField(blank=True, help_text='Profesional que aplicó la vacuna', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(help_text='Nombre del medicamento', max_length=200)),
                ('dosis', models.CharField(help_text='Dosis prescrita', max_length=100)),
                ('frecuencia', models.CharField(help_text='Frecuencia de administración', max_length=100)),
                ('duracion', models.CharField(blank=True, help_text='Duración del tratamiento', max_length=100, null=True)),
                ('indicacion', models.TextField(help_text='Indicación médica')),
                ('fecha_prescripcion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('profesional_salud', models.CharField(blank=True, help_text='Profesional que prescribió', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el medicamento está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-fecha_prescripcion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_familiares', models.TextField(blank=True, help_text='Antecedentes familiares relevantes', null=True)),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas', null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Medicamentos que toma actualmente', null=True)),
                ('condiciones_cronicas', models.TextField(blank=True, help_text='Condiciones médicas crónicas', null=True)),
                ('cirugias_previas', models.TextField(blank=True, help_text='Cirugías o procedimientos previos', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
            },
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagenología'), ('funcional', 'Funcional'), ('endoscopia', 'Endoscopía'), ('otros', 'Otros')], max_length=20)),
                ('nombre_examen', models.CharField(help_text='Nombre específico del examen', max_length=200)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('interpretacion', models.TextField(blank=True, help_text='Interpretación médica del resultado', null=True)),
                ('profesional_solicitante', models.CharField(blank=True, max_length=200, null=True)),
                ('profesional_interpretador', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_medicos', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Examen Médico',
                'verbose_name_plural': 'Exámenes Médicos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
