# Generated by Django 4.2.7 on 2025-11-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0003_grupoetnico_remove_persona_grupo_familiar_and_more'),
        ('salud', '0002_vacuna_medicamento_historialmedico_examenmedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertasalud',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_salud', to='poblacion.persona'),
        ),
    ]
