# Generated by Django 4.2.7 on 2025-10-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poblacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(help_text='Tipo de reporte social (ej: apoyo social, condiciones)', max_length=100)),
                ('datos_agregados', models.JSONField(help_text='Datos agregados del reporte social en formato JSON')),
                ('fecha_reporte', models.DateField()),
                ('generado_por', models.CharField(help_text='Usuario que generó el reporte', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_sociales', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Reporte Social',
                'verbose_name_plural': 'Reportes Sociales',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='ReporteSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(help_text='Tipo de reporte (ej: resumen salud, indicadores)', max_length=100)),
                ('datos_agregados', models.JSONField(help_text='Datos agregados del reporte en formato JSON')),
                ('fecha_reporte', models.DateField()),
                ('generado_por', models.CharField(help_text='Usuario que generó el reporte', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_salud', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Reporte de Salud',
                'verbose_name_plural': 'Reportes de Salud',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='ReporteEncuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(help_text='Tipo de reporte de encuestas (ej: resultados encuesta, análisis)', max_length=100)),
                ('datos_agregados', models.JSONField(help_text='Datos agregados del reporte de encuestas en formato JSON')),
                ('fecha_reporte', models.DateField()),
                ('generado_por', models.CharField(help_text='Usuario que generó el reporte', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_encuestas', to='poblacion.persona')),
            ],
            options={
                'verbose_name': 'Reporte de Encuestas',
                'verbose_name_plural': 'Reportes de Encuestas',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
