# Generated by Django 5.2.7 on 2025-11-29 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteencuestas',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='reportesalud',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='reportesocial',
            name='persona',
        ),
        migrations.AlterField(
            model_name='reporteencuestas',
            name='generado_por',
            field=models.ForeignKey(help_text='Usuario que generó el reporte', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportesalud',
            name='generado_por',
            field=models.ForeignKey(help_text='Usuario que generó el reporte', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportesocial',
            name='generado_por',
            field=models.ForeignKey(help_text='Usuario que generó el reporte', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
