# Generated by Django 4.2.7 on 2025-11-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_remove_reporteencuestas_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteencuestas',
            name='generado_por',
            field=models.CharField(help_text='Usuario que generó el reporte', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportesalud',
            name='generado_por',
            field=models.CharField(help_text='Usuario que generó el reporte', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportesocial',
            name='generado_por',
            field=models.CharField(help_text='Usuario que generó el reporte', max_length=100),
        ),
    ]
