# Generated by Django 4.2.7 on 2025-10-30 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poblacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado del Programa',
                'verbose_name_plural': 'Estados de los Programas',
            },
        ),
        migrations.CreateModel(
            name='ProgramaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('beneficiarios', models.ManyToManyField(related_name='programas_sociales', to='poblacion.persona')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.estadoprograma')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa Social',
                'verbose_name_plural': 'Programas Sociales',
            },
        ),
        migrations.CreateModel(
            name='CoberturaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=225)),
                ('area_nombre', models.CharField(blank=True, max_length=100)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.programasocial')),
            ],
            options={
                'verbose_name': 'Cobertura de Programa',
                'verbose_name_plural': 'Coberturas de Programa',
            },
        ),
        migrations.CreateModel(
            name='ActividadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.programasocial')),
            ],
            options={
                'verbose_name': 'Actividad Social',
                'verbose_name_plural': 'Actividades Sociales',
            },
        ),
        migrations.CreateModel(
            name='ProgramaBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('egresado', 'Egresado')], default='activo', max_length=10)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poblacion.persona')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.programasocial')),
            ],
            options={
                'verbose_name': 'Beneficiario de Programa',
                'verbose_name_plural': 'Beneficiarios de Programas',
                'unique_together': {('programa', 'persona')},
            },
        ),
    ]
