# Generated by Django 4.2.7 on 2025-10-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programasocial',
            name='beneficiarios',
            field=models.ManyToManyField(blank=True, related_name='programas_sociales', to='poblacion.persona'),
        ),
    ]
