# Generated by Django 5.2.7 on 2025-11-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_programasocial_beneficiarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='programasocial',
            name='beneficiarios_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Beneficiarios'),
        ),
    ]
