# Generated by Django 5.2.7 on 2025-11-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0002_alter_persona_genero'),
        ('social', '0003_programasocial_beneficiarios_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Rol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol de Autoridad',
                'verbose_name_plural': 'Roles de Autoridad',
            },
        ),
        migrations.CreateModel(
            name='TipoAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Autoridad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Autoridad',
                'verbose_name_plural': 'Tipos de Autoridad',
            },
        ),
        migrations.CreateModel(
            name='AutoridadComunitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_mandato', models.DateField(verbose_name='Fecha Inicio Mandato')),
                ('fecha_fin_mandato', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Mandato')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poblacion.persona', verbose_name='Persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.rolautoridad', verbose_name='Rol')),
                ('tipo_autoridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.tipoautoridad', verbose_name='Tipo de Autoridad')),
            ],
            options={
                'verbose_name': 'Autoridad Comunitaria',
                'verbose_name_plural': 'Autoridades Comunitarias',
                'ordering': ['persona__primer_apellido', 'persona__primer_nombre'],
            },
        ),
    ]
