# Generated by Django 5.2.7 on 2025-11-10 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0002_alter_persona_genero'),
        ('social', '0004_rolautoridad_tipoautoridad_autoridadcomunitaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Color (Hex/CSS)')),
            ],
            options={
                'verbose_name': 'Estado de Actividad',
                'verbose_name_plural': 'Estados de Actividad',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Actividad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono (Bootstrap)')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
            },
        ),
        migrations.AlterModelOptions(
            name='actividadsocial',
            options={'verbose_name': 'Actividad Social (Legacy)', 'verbose_name_plural': 'Actividades Sociales (Legacy)'},
        ),
        migrations.CreateModel(
            name='ActividadComunitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Fin')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Máxima')),
                ('asistentes_confirmados', models.PositiveIntegerField(default=0, verbose_name='Asistentes Confirmados')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto')),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Real')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('asistentes_registrados', models.ManyToManyField(blank=True, related_name='actividades_registradas', to='poblacion.persona', verbose_name='Asistentes Registrados')),
                ('organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.estadoactividad', verbose_name='Estado')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.tipoactividad', verbose_name='Tipo de Actividad')),
            ],
            options={
                'verbose_name': 'Actividad Comunitaria',
                'verbose_name_plural': 'Actividades Comunitarias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Asistencia Confirmada')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.actividadcomunitaria', verbose_name='Actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poblacion.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Asistencia a Actividad',
                'verbose_name_plural': 'Asistencias a Actividades',
                'unique_together': {('actividad', 'persona')},
            },
        ),
    ]
