# Generated by Django 5.2.7 on 2025-11-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_estadoactividad_tipoactividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcomunitaria',
            name='organizador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organizador'),
        ),
    ]
