# Generated by Django 5.2.7 on 2025-11-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20251110_0111'),
    ]

    operations = [
    ]
