# Generated by Django 5.2.7 on 2025-11-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_fix_serializer_queryset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcomunitaria',
            name='organizador',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Organizador'),
        ),
    ]
