# Generated by Django 5.2.7 on 2025-11-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_remove_null_from_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='programasocial',
            name='tipo_programa',
            field=models.CharField(choices=[('educacion', 'Educación'), ('cultural', 'Cultural'), ('salud', 'Salud'), ('infraestructura', 'Infraestructura'), ('seguridad_alimentaria', 'Seguridad Alimentaria')], default='educacion', max_length=25, verbose_name='Tipo de Programa'),
        ),
    ]
