# Generated by Django 4.2.7 on 2025-11-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
    ]
