# Generated by Django 5.2.7 on 2025-11-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0002_alter_persona_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEtnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo Étnico',
                'verbose_name_plural': 'Grupos Étnicos',
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='grupo_familiar',
        ),
        migrations.AddField(
            model_name='persona',
            name='grupo_etnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poblacion.grupoetnico'),
        ),
        migrations.DeleteModel(
            name='GrupoFamiliar',
        ),
    ]
