# Generated by Django 4.2.7 on 2025-11-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0001_initial'),
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuestas', to='poblacion.persona'),
        ),
    ]
