# Generated by Django 4.2.7 on 2025-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_respuesta_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='token',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
