# Generated by Django 4.2.7 on 2025-11-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_encuesta_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='token',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='persona',
        ),
    ]
