# Generated by Django 4.2.7 on 2025-11-10 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poblacion', '0002_alter_persona_genero'),
        ('encuestas', '0004_remove_encuesta_token_remove_respuesta_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuestas', to='poblacion.persona'),
        ),
    ]
